name: model-training
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Model training
        run: python ./src/train.py
      - name: Model upload
        uses: actions/upload-artifact@v3
        with:
          name: upload-the-model
          path: ./data/models/auto-mpg.sav
      - name: Automated testing
        run: python -m pytest
